Vagrant.configure("2") do |config|
  config.vm.box = "generic/rocky9"
  config.vm.hostname = "control-node"
  config.vm.network "private_network", ip: "192.168.56.2"
  config.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_udp: false
  config.vm.provision "shell", path: "provision.sh"
end
