- name: Upgrade de todos os pacotes do s.os
  yum:
    name: '*'
    state: latest
- name: Configurar hosts lab ansible
  lineinfile: 
    path: /etc/hosts
    line: "{{item}}" 
    state: present
    loop:
      - "192.168.56.2 control-node"
      - "192.168.56.3 app01"
      - "192.168.56.4 db01"
